In [3]:
import numpy as np
def upper_triangular(A,b):
    n, _ = A.shape
    for it1 in range(n-1):
        for it2 in range(it1+1, n):
            m= A[it2, it1]/ A[it1, it1]
            A[it2, ] = A[ it2, ] - A[it1, ] * m
            b[it2] = b[it2] - b[it1] * m
        
    return A,b
def gauss(A,b):
    A,b = upper_triangular(A,b)
    n, _ = A.shape
    x=np.zeros(n)
    for it in range(n-1, -1, -1):
        x[it]= (b[it] - np.matmul(A[it,it+1:] , x[it+1:])) / A[it, it]
    return x

In [7]:
 a = np.array([[5., 8., 5.],
                  [4., 2., 7.],
                  [8., 5., 8.]])
b = np.array([48., 43., 69.])

print(gauss(a, b))

[5. 1. 3.]


In [10]:
a = np.array([[3. , 4. , 1. ],
            [1. , 0. , 1. ],
            [2. , 3. , 2. ]])
b = np.array([3. , 3. , 1.5])

print(gauss(a,b))

[ 3.00000000e+00 -1.50000000e+00  1.48029737e-16]


In [17]:
a = np.array([[1. , 0.1 , 0.1**2, 0.1**3],
              [1. , 0.3 , 0.3**2, 0.3**3],
              [1. , 0.6 , 0.6**2, 0.6**3],
              [1. , 1.2 , 1.2**2, 1.2**3]])
x = np.zeros(4)
b = np.array([1.023 , 1.261, 2.368 , 9.064])
print(gauss(a,b))

[1. 0. 2. 3.]


In [26]:
a = np.array([[-1. , 2. , -3. ],
              [3. , -4. , -2. ],
              [-4. ,-4. , 4.]])
b = np.array([[10.],
             [14.],
             [-15.]])
c = np.array([[3.],
             [3.],
             [-3.]])
d = np.array([[-4.],
             [0.],
             [-1.]])
a = a.transpose()

x = d + 2*c - b
print(gauss(a, x))


[-0.  0.  2.]


In [20]:
a = np.array([[-3. ,-2. , -3.],
              [-3. , 0. , -5.],
              [-1. , -4. , 5.]])
b = np.array([11. , 7. , 5.])
print(gauss(a,b))

[ 1. -4. -2.]
